### ISSUE TITLE
Major performance increase by shortening URL regex

### ISSUE THREAD

**Issue by inorganik** [SebastienThiebaud/STTweetLabel#115]
I am using STTweetLabel in a UITableView. In my case, there is one STTweetLabel per cell; each one detects three types of hotwords, including URL. I noticed that when I scrolled kind of fast, the performance wasn't that good, the scrolling was jumpy. I have been testing on an iPhone 5s and 6, both showed jumpy scrolling.

By simply changing the URL regex in `STTweetLabel.m` to a shorter regex, I got a major performance increase. I can scroll super fast and it's super smooth. Here's the regex I used instead:

```
#define STURLRegex @"(https?:\\/\\/)?([\\w\\-])+\\.{1}([a-zA-Z]{2,63})([\\/\\w-]*)*\\/?\\??([^#\\n\\r]*)?#?([^\\n\\r]*)"
```
You can test the regex here: http://regexr.com/39p0t

EDIT: please note regex fix below.

**Comment by cognitiveflux** [comment]
Has anyone tested using `NSDataDetector ` with `NSTextCheckingTypeLink`?  It would also remove the need for this project to maintain or test for regex, and it would allow the future implementation of other data types (e.g. all those supported by `NSDataDetector`).

**Comment by cognitiveflux** [comment]
@SebastienThiebaud @inorganik 

I forked and branched `develop` and created 87c835518588c37dcd73690dccbd8e06a9e456ae implementing `NSDataDetector` for link detection.  I added a workaround so that the `test_setTextAndGetHotWords_setTextWithOneEncapsulateLinkWithSpecialCharacters_hotWords` test would pass because `NSDataDetector` will only detect `(http://foo.com/?arg=bar)` but not `(http://foo.com/?arg=bar(baz))`.

All other tests pass except `test_setTextAndGetHotWords_setTextWithOneLinkWithSpecialCharacters_hotWords` because it is my understanding that `[]` are valid characters per [RFC3986](https://tools.ietf.org/html/rfc3986#page-12), correct?

If this is sufficient I can remove that test and submit a pull request including all the changes.

How did you benchmark the performance previously?

For a future pull request my hope is to be able to use the `NSURL` object returned from `NSDataDetector` and pass it back to the detection block so that one could simply call `[[UIApplication sharedApplication] openURL:url];`.  This saves the need for doing any URL parsing or creation yet again in the detection block and allows for easy external app integration; for example, simply including `mailto` in the allowed protocols would allow `"string with email@domain.com"` to automatically be parsed into a NSURL object that would open the `Mail` app without any other application changes.  Thoughts?

**Comment by cognitiveflux** [comment]
Update -- after benchmarking (n = 1000) it appears the original regex is faster than `NSDataDetector`, bummer.  Even though the proposed regex doesn't match all cases, just for comparison I also included it:

```
            user        system    total        real
orig       10.730000   0.110000  10.840000 ( 10.909613)
nsdd       11.290000   1.210000  12.500000 ( 12.603403)
new_regex  4.200000    0.090000   4.290000 (  4.416512)
```

**Comment by inorganik** [comment]
Interesting... that's pretty cool. Thanks for sharing!

**Comment by SebastienThiebaud** [comment]
A pretty big refactoring is on the way. With some performance improvements.

**Comment by gregmurray** [comment]
Awesome Sebastian!  When do you think the new version will be pushed?  Just found STTweetLabel and am excited to implement it.

**Comment by SebastienThiebaud** [comment]
`3.1.18` is available with a ton of fixes (auto layout, performances)
